# Generated by Django 3.2.5 on 2022-01-04 15:52

from django.db import migrations, models
import game.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=game.models.generate_code, max_length=5, unique=True)),
                ('host', models.CharField(max_length=50, unique=True)),
                ('game_time', models.TimeField(verbose_name='Game time:')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.CharField(default=game.models.make_board, max_length=200)),
                ('host_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('player_id', models.UUIDField(default=None, editable=False, null=True, unique=True)),
                ('host_starts', models.BooleanField(default=game.models.random_bool)),
                ('host_time', models.TimeField(null=True, verbose_name='Host time:')),
                ('player_time', models.TimeField(null=True, verbose_name='Player time:')),
                ('host_nickname', models.CharField(max_length=16, null=True)),
                ('player_nickname', models.CharField(max_length=16, null=True)),
                ('public', models.BooleanField(default=False)),
            ],
        ),
    ]
