# Generated by Django 3.2.5 on 2021-09-21 14:27

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(
                    default=game.models.make_board, max_length=100)),
                ('host', models.CharField(max_length=50, unique=True)),
                ('bot_level', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(
                    default=game.models.generate_code, max_length=5, unique=True)),
                ('host', models.CharField(max_length=50, unique=True)),
                ('game_time', models.TimeField(verbose_name='Player time:')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
