# Generated by Django 3.2.5 on 2021-11-22 12:17

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='board',
        ),
        migrations.RemoveField(
            model_name='game',
            name='bot_level',
        ),
        migrations.AddField(
            model_name='room',
            name='board',
            field=models.CharField(default=game.models.make_board, max_length=200),
        ),
    ]
